version: 2

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

jobs:
  flake8:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: pip install flake8 --user
      - run:
          name: Run flake8
          command: flake8 fabric_plugin

  unittests:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install --user -r test-requirements.txt
            pip install --user .
      - run:
          name: run unittests
          command: |
            ~/.local/bin/pytest \
               --cov fabric_plugin --cov-report term-missing \
              --junitxml=test-results/fabric_plugin.xml \
              fabric_plugin/tests
      - store_test_results:
          path: test-results

workflows:
  version: 2
  tests:
    jobs:
      - flake8
      - unittests
